import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_excel('data.xlsx')
df.to_csv('data.csv', encoding='utf-8', index=None)
df.set_index('sec')['ch1'].plot(color='red', alpha=0.5, ylabel='ch1, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch2'].plot(color='blue', alpha=0.5, ylabel='ch2, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch3'].plot(color='red', alpha=0.5, ylabel='ch3, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch4'].plot(color='blue', alpha=0.5, ylabel='ch4, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch5'].plot(color='red', alpha=0.5, ylabel='ch5, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch6'].plot(color='blue', alpha=0.5, ylabel='ch6, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch7'].plot(color='red', alpha=0.5, ylabel='ch7, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch8'].plot(color='blue', alpha=0.5, ylabel='ch8, mA', xlabel='time, mSec')
plt.show()
df.set_index('sec')['ch1'].plot(color='blue', ylabel='mA', xlabel='mSec')
df.set_index('sec')['ch2'].plot(color='red', xlabel='mSec')
df.set_index('sec')['ch3'].plot(color='yellow', xlabel='mSec')
df.set_index('sec')['ch4'].plot(color='purple', xlabel='mSec')
df.set_index('sec')['ch5'].plot(color='orange', xlabel='mSec')
df.set_index('sec')['ch6'].plot(color='green', xlabel='mSec')
df.set_index('sec')['ch7'].plot(color='black', xlabel='mSec')
df.set_index('sec')['ch8'].plot(color='grey', xlabel='mSec')
plt.legend(title='Parameter where:')
plt.show()
